spring:
  application:
    name: BroMatch
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 010609dy
    url: jdbc:mysql://localhost:3306/bromatch
server:
  port: 8081
